app/models/instrument.rb
app/models/jamm.rb
app/models/participation.rb
app/models/skill.rb
app/models/user.rb
config/routes.rb
db/migrate/20181204170220_create_instruments.rb
db/migrate/20181204170827_create_jamms.rb
db/migrate/20181204171157_create_skills.rb
db/migrate/20181204171416_create_participants.rb
db/migrate/20181204174419_rename_participants_to_participations.rb
db/schema.rb
db/schema.xml
test/models/instrument_test.rb
test/models/jamm_test.rb
test/models/participant_test.rb
test/models/skill_test.rb

Models have been generated , 
I also add some validations in it

Models and validations done

---

Gemfile
Gemfile.lock
app/controllers/instruments_controller.rb
app/controllers/jamms_controller.rb
app/models/instrument.rb
app/models/jamm.rb
app/models/participation.rb
app/models/user.rb
app/views/instruments/create.html.erb
app/views/instruments/destroy.html.erb
app/views/instruments/edit.html.erb
app/views/instruments/index.html.erb
app/views/instruments/new.html.erb
app/views/instruments/show.html.erb
app/views/instruments/update.html.erb
app/views/jamms/create.html.erb
app/views/jamms/destroy.html.erb
app/views/jamms/edit.html.erb
app/views/jamms/index.html.erb
app/views/jamms/new.html.erb
app/views/jamms/show.html.erb
app/views/jamms/update.html.erb
db/migrate/20181205133229_remove_creator_from_participations.rb
db/migrate/20181205133711_add_creator_to_jamms.rb
db/migrate/20181205135428_change_duration_to_be_integer_in_jamms.rb
db/schema.rb
db/seeds.rb
test/controllers/instruments_controller_test.rb
test/controllers/jamms_controller_test.rb

Seeds done ( Tested )
Controllers : Jamms and Instruments are generated 
Maybe i will make some modifications in Instruments controller.

Seeds done and tested, Jamms and Instrument Controllers are generated

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_login_form.scss
app/assets/stylesheets/components/_navbar.scss

Small changes to Navbar and button

subtle changes to navbar

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/controllers/participations_controller.rb
app/controllers/skills_controller.rb
app/models/instrument.rb
app/policies/application_policy.rb
app/policies/skill_policy.rb
app/views/pages/dashboard.html.erb
app/views/skills/_skill_form.html.erb
app/views/skills/create.html.erb
app/views/skills/destroy.html.erb
app/views/skills/edit.html.erb
app/views/skills/new.html.erb
app/views/skills/show.html.erb
app/views/skills/update.html.erb
config/routes.rb
db/migrate/20181206144631_change_level_to_be_string_in_skills.rb
db/schema.rb
db/schema.xml
db/seeds.rb

it needs some modification in order to add categories to the Skills form

Skills Controller and view are Done

---

app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/components/_jam_hover_option.scss
app/assets/stylesheets/components/_tabs.scss
app/javascript/components/tabs.js
app/javascript/packs/application.js
app/views/pages/_instruments_tab_card.html.erb
app/views/pages/dashboard.html.erb
app/views/shared/_navbar.html.erb

Created cards and few fixes for dashboard instruments view

instruments dashboard page cards

---

app/controllers/jamms_controller.rb
app/policies/jamm_policy.rb
app/views/jamms/edit.html.erb
app/views/jamms/new.html.erb
app/views/jamms/show.html.erb
test/policies/jamm_policy_test.rb

Creation of a jamm. Edition of a jamm. Suppression of a jamm. Show of a jamm.

jamm feature ok

---

app/controllers/pages_controller.rb
app/models/instrument.rb
app/policies/jamm_policy.rb
app/views/pages/dashboard.html.erb

Adding some links to permit navigation throught the app + some view problems fixed (All Jams was blank page). Now the jams created by the user are on the dashboard and other jams on Jamming Sessions. User cannot delete or edit other sessions anymore

fixing some links and view problem

---

app/controllers/participations_controller.rb
app/views/participations/create.html.erb

You cannot join a session which is full anymore
As a creator you cannot accept more participants specified by the capacity anymore

logic capicity ok

---

app/controllers/participations_controller.rb
app/policies/jamm_policy.rb
app/policies/participation_policy.rb
app/views/participations/create.html.erb

Now if the session is full the join button disappear
pundit error when unlogged user wants to see all jams is fixed

pundit precision

---

app/policies/jamm_policy.rb

jamm policy problem fixed (def update? misplaced end)

fixing little bug

---

app/views/jamms/_participation.html.erb

nothing special just showing the username on the jam page

username participant shown

---

app/controllers/jamms_controller.rb
app/models/jamm.rb
app/views/jamms/new.html.erb

Creation jam form was blocking the navbar
Capacity and duration cannot be nil or negative

capacity and duration cannot be negative

---

app/views/jamms/show.html.erb
app/views/pages/_jamms_tab_card.html.erb
app/views/pages/home.html.erb

added hours to jamms show and index
start now linked to all jamms
email address truncated on jamms show

added hours, start now on home link and truncate email

---

app/controllers/participations_controller.rb

You are now redirected to add skill if you want to join a jam without skill

redirected to add skill if no skill

---

app/controllers/messages_controller.rb
app/policies/message_policy.rb
app/views/jamms/show.html.erb
test/policies/message_policy_test.rb

a creator can now delete messages

a creator can delete messages

---

app/controllers/pages_controller.rb
app/views/pages/dashboard.html.erb

Added "My participations" and "My applications" in All Jams in Dashboard

more precise my jams

---

app/controllers/jamms_controller.rb
app/views/jamms/index.html.erb

Added a search bar to let the user filter the jams by location

search by location

---

app/controllers/pages_controller.rb

Les doublons dans le dashboard My Jamms ont été fixé

doublons dans dashboard fixes

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_cards.scss
app/views/devise/registrations/edit.html.erb
app/views/jamms/index.html.erb
app/views/pages/_instruments_tab_card.html.erb
app/views/pages/_jamms_tab_card.html.erb
app/views/shared/_navbar.html.erb
config/webpacker.yml

Jamms index + User edit views are done

Jamms index

---

app/controllers/reviews_controller.rb
app/policies/jamm_policy.rb
app/views/pages/_jamms_tab_card.html.erb

FULL appear on jamms_card if the jamm is full
fixed the issue with review (you could review even if you weren't there!)
edition and update aborted

some stuff

---

app/assets/stylesheets/components/_index.scss
app/views/jamms/_participation.html.erb

Participation hover with Username, instrument and status tooltip added.
User Accept or decline/pending icon also added next to avatar

participation hover and status added

---

app/views/jamms/_participation.html.erb

Thumb crop formatting added to participants avatar
Icons corrected so only x and tick for acceptance status has border

Avatar thumb crop added

---

app/views/skills/_skill_form.html.erb

Adding new skills form formatted

skills new form formatted

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/config/_fonts.scss

Font size of 'SoulJam' increased to 60px and font-family changed

Homepage Souljam font changed

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/components/_navbar.scss

Footer on homepage colour changed

footer homepage to gray

---

app/controllers/jamms_controller.rb
app/policies/jamm_policy.rb
app/views/jamms/show.html.erb
app/views/reviews/new.html.erb

Review when title is empty is now in bold
Review rating specify that it is included between 0 and 5
Cannot delete a past jam anymore

review styling, delete desactivated for the past sessions

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_cards.scss
app/assets/stylesheets/components/_jam_hover_option.scss
app/assets/stylesheets/components/_login_form.scss
app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/components/_tabs.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss
app/views/jamms/_participation.html.erb
public/404.html
public/422.html
public/500.html

Main scheme colour changed from turquoise to navy blue.
Homepage to white
Participants icon moved closer in respect to avatar, also now set to thumb with instrument pic removed.

colour change and participants statusicon move

---

app/assets/stylesheets/components/_cards.scss

fix to index view, height 50%, width 100%

fix to index cards show
